name: build
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Updated to Node.js version 20
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@talis-art'  # Replace with your GitHub username or organization

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter "@talis-art/*" build

      - name: Publish
        run: pnpm publish --filter "@talis-art/*" --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using GitHub token for authentication
